### ISSUE TITLE
Ads appear on chats although I purchased a premium license

### ISSUE THREAD

**Issue by wwwyaron** [Gurjot95/DirectChat-Feedback#7] opened 2020-07-28 09:29 UTC
Only when I open Directchat app itself, it disappears after a few seconds.

**Comment by Gurjot95** [comment] 2020-07-28 09:34
I will be fixing that in next update. Also duplicate of #6

Regards
Gurjot Singh

**Comment by wwwyaron** [comment] 2020-07-28 09:57
Thank you. When can we expect that?

**Comment by Gurjot95** [comment] 2020-07-31 12:22
Should be fixed now in latest update. Closing the issue now.

**Closed as completed by Gurjot95** 2020-07-31 12:22 UTC
